name: Deployment workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: docker build -t secret_kubernetes_uacademy . && docker tag secret_kubernetes_uacademy zeromaxinc/secret_kubernetes_uacademy 
  
    - name: Docker push
      run: docker push zeromaxinc/secret_kubernetes_uacademy

    - name: Configuration Git
      run: git config --global user.email "zeromax.adm@gmail.com" && git config --global user.name "quantumitllc"
